version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mencl_db
    hostname: db
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/db/conf.d:/etc/mysql/conf.d
      - ./.docker/db/log/mysql:/var/log/mysql
  api:
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/api
    depends_on:
      - db
